# Default values for esap.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: esap
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: esap.cta.cscs.ch
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - hosts:
        - esap.cta.cscs.ch
      secretName: esap-prod-cert

extraEnv:
  OIDC_OP_JWKS_ENDPOINT: "OIDC_OP_JWKS_ENDPOINT"
  LOGIN_REDIRECT_URL: "https://esap-gui.test-cta-cscs.odahub.io/esap-gui/login"
  LOGOUT_REDIRECT_URL: "https://esap-gui.test-cta-cscs.odahub.io/esap-gui/logout"
  LOGIN_REDIRECT_URL_FAILURE: ""
